Repository codersforcauses/penni, pull requests merged in 2024-07, with the labels that each got.

#59 Issue 42 global css style for font
  client/src/pages/_app.tsx
  client/src/pages/font.tsx
  client/src/pages/index.tsx
  client/src/styles/globals.css
  client/src/styles/styles.css
  client/tailwind.config.ts
Labels: frontend, priority:high

#55 Issue 39 create auto test cases for database models
  server/app/migrations/0001_initial.py
  server/app/migrations/0002_alter_users_options_remove_bids_amount_and_more.py
  server/app/migrations/0003_rename_estimated_price_tasks_budget.py
  server/app/models.py
  server/app/test_bids_payments.py
  server/app/test_task.py
  server/app/test_usr_profiles.py
  server/app/tests.py
Labels: work in progress

#77 Issue 33 task card component
  client/public/icons/calendar.svg
  client/public/icons/clock.svg
  client/public/icons/marker.svg
  client/src/components/ui/TaskCard.tsx
  client/src/pages/hello.tsx
  client/src/pages/index.tsx
  client/src/pages/taskcard.tsx
Labels: frontend

#107 Issue 70 request to add more button variant and create a button reference example page
  client/components.json
  client/src/components/ui/button.tsx
  client/src/components/ui/icons.tsx
  client/src/pages/component-showcase.tsx
  client/tailwind.config.ts
Labels: frontend, difficulty:easy, priority:high

#105 Issue 67 create mock data for database when setting up server
  server/app/__init__.py
  server/app/apps.py
  server/app/fixtures.py
  server/app/test_task.py
Labels: backend

#66 Issue 35 task details
  client/src/components/task-details.tsx
  client/src/components/ui/text.tsx
  client/src/pages/index.tsx
Labels: frontend

#118 Issue 90 report a problem page
  client/public/icons/arrow_back.svg
  client/public/icons/delete.svg
  client/public/icons/upload_image.svg
  client/src/components/ui/header.tsx
  client/src/components/ui/upload-images.tsx
  client/src/components/ui/write-in.tsx
  client/src/pages/account/report.tsx
Labels: enhancement, frontend

#97 Issue 79 create login/signup view
  server/api/settings.py
  server/api/urls.py
  server/app/migrations/0001_initial.py
  server/app/models.py
  server/app/serializers.py
  server/app/test_auth.py
  server/app/urls.py
  server/app/views.py
  server/poetry.lock
  server/pyproject.toml
Labels: backend

#131 Create bidder offer card for poster to view
  client/public/bidder-exmaple-profile.svg
  client/src/components/ui/bidder-offer-card.tsx
  client/src/pages/component-showcase.tsx
Labels: frontend

#128 Add poster side task card
  client/src/components/ui/poster/task-card.tsx
  client/src/pages/component-showcase.tsx
Labels: frontend

#141 Complete Poster Task pages with Router Navigation and data sharing between pages.
  client/public/back.svg
  client/public/bidder-exmaple-profile1.svg
  client/public/bidder-exmaple-profile2.svg
  client/public/bidder-exmaple-profile3.svg
  client/public/bidder-exmaple-profile4.svg
  client/public/profile-2.svg
  client/public/task-blank-page.svg
  client/src/components/ui/bidder-offer-card.tsx
  client/src/components/ui/poster/task-card.tsx
  client/src/components/ui/task-top-bar.tsx
  client/src/pages/poster/tasks/[taskid]/[bidderid]/bid-details.tsx
  client/src/pages/poster/tasks/[taskid]/task-details.tsx
  client/src/pages/poster/tasks/create-task.tsx
  client/src/pages/poster/tasks/index.tsx
  client/src/pages/poster/tasks/new-task.tsx
  client/src/pages/poster/tasks/task-list.tsx
  client/src/pages/signup.tsx
Labels: frontend, difficulty:hard

#145 Bugfix import clause dependency error
  client/src/pages/poster/tasks/[taskid]/task-details.tsx
Labels: bug

#102 Issue 78 create tasks view
  server/api/urls.py
  server/app/serializers.py
  server/app/test_task_views.py
  server/app/urls.py
  server/app/views.py
Labels: backend

#127 Issue 94 create profile http api
  .gitignore
  server/api/settings.py
  server/api/urls.py
  server/app/migrations/0002_alter_profiles_avatar_url.py
  server/app/migrations/0003_alter_profiles_avatar_url.py
  server/app/models.py
  server/app/serializers.py
  server/app/test_usr_profiles.py
  server/app/urls.py
  server/app/views.py
  server/poetry.lock
  server/pyproject.toml
Labels: backend, work in progress

#132 Create logging function with file, in settings.py
  server/api/settings.py
  server/app/middleware/__init__.py
  server/app/middleware/request_log.py
Labels: backend, difficulty:easy

#143 Issue 110 - Warn about required fields not being filled in in forms
  client/src/components/ui/form.tsx
  client/src/components/ui/inputs.tsx
Labels: enhancement, frontend

#173 [PATCH] Fix backend API issues, refactor database, and improve structure
  client/src/pages/sign-in.tsx
  server/api/settings.py
  server/api/urls.py
  server/app/__init__.py
  server/app/admin.py
  server/app/apps.py
  server/app/fixtures.py
  server/app/middleware/request_log.py
  server/app/migrations/0001_initial.py
  server/app/migrations/0002_alter_profiles_avatar_url.py
  server/app/migrations/0002_remove_tasks_location_tasklocation.py
  server/app/migrations/0003_alter_bids_status_alter_tasks_status_and_more.py
  server/app/migrations/0003_alter_profiles_avatar_url.py
  server/app/models.py
  server/app/permissions.py
  server/app/serializers.py
  server/app/test_auth.py
  server/app/test_bids_payments.py
  server/app/test_task.py
  server/app/test_task_views.py
  server/app/test_usr_profiles.py
  server/app/urls.py
  server/app/views.py
  server/poetry.lock
  server/pyproject.toml
Labels: backend, difficulty:hard

#172 Issue 65 replace all font styling with global font classes
  client/package-lock.json
  client/package.json
  client/src/components/ui/button.tsx
  client/src/components/ui/callout.tsx
  client/src/components/ui/signup/avatar.tsx
  client/src/components/ui/signup/bio.tsx
  client/src/components/ui/signup/check-unique.ts
  client/src/components/ui/signup/main-page.tsx
  client/src/components/ui/signup/multi-step-form.tsx
  client/src/components/ui/signup/progress-bar.tsx
  client/src/components/ui/signup/pw.tsx
  client/src/components/ui/signup/regex.ts
  client/src/components/ui/signup/welcome.tsx
  client/src/pages/signup.tsx
  client/tailwind.config.ts
  server/app/fixtures.py
  server/app/urls.py
  server/app/views.py
Labels: enhancement, frontend, priority:medium, difficulty:hard
